(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'f5f8b242-e2dc-4a72-873a-c50da511cee9-bootstrap-container',
          componentName:'ContactForm2',
          props:props,
          context:context,
          contextKey:'context-f5f8b242-e2dc-4a72-873a-c50da511cee9-bootstrap-container',
          radpack:false
        });
      })({"formTitle":"Ask a question or report a bug\u002Fissue","formFields":[{"type":"SINGLE_LINE","label":"Name","required":false},{"type":"EMAIL","label":"Email","validation":"email","required":true,"replyTo":true},{"type":"MULTI_LINE","label":"Message","required":true},{"type":"SUBMIT","label":"Send","required":false}],"blankInfo":false,"formSubmitHost":"https:\u002F\u002Fcontact.apps-api.instantpage.secureserver.net","recaptchaEnabled":true,"recaptchaType":"V3","domainName":"pokerladder.uk","formSuccessMessage":"{\"blocks\":[{\"key\":\"fmmkt\",\"text\":\"Thank you for your message! We will get back to you within ASAP.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}","formEnabled":true,"websiteId":"79791148-6c18-45bf-b9ce-f15cb6b4310f","pageId":"19756ec4-e4cf-4fdf-a713-8a76c75f0b75","accountId":"b2e2d193-ef17-11ea-8216-3417ebe73f23","staticContent":{"today":"Today","submitButtonLoadingLabel":"Sending","contactFormResponseErrorMessage":"Something went wrong while sending your message, please try again later","phoneValidationErrorMessage":"Please enter a valid phone number.","defaultCancelButtonLabel":"Cancel","byAppointment":"By Appointment","defaultSubmitButtonLabel":"Send","unsupportedFileType":"Unsupported file type","maxFileCountLimit":"Only {0} files are allowed","closed":"Closed","attachments":"Attachments","termsOfSerivce":"Terms of Service","attachFiles":"Attach Files","recaptchaDisclosure":"This site is protected by reCAPTCHA and the Google {privacyPolicy} and {termsOfSerivce} apply.","emailValidationErrorMessage":"Please enter a valid email address.","mapCTA":"Get directions","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Please fill in this required field","openToday":"Open today","couldNotAttach":"Could not attach the following file(s)","totalFileSizeLimit":"Total files would exceed {0} limit","privacyPolicy":"Privacy Policy","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms","fileSizeLimit":"File exceeds {0} limit","emailMaxCountValidationErrorMessage":"Your email address is too long"},"emailOptInEnabled":false,"emailOptInHidden":false,"emailOptInMessage":"Sign up for our email list for updates, promotions, and more.","emailConfirmationMessage":"We've sent you a confirmation email, please click the link to verify your address.","widgetId":"f5f8b242-e2dc-4a72-873a-c50da511cee9","section":"default","category":"accent","locale":"en-GB","renderMode":"PUBLISH"},{"widgetId":"f5f8b242-e2dc-4a72-873a-c50da511cee9","widgetType":"CONTACT","widgetPreset":"contact2","section":"default","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"Content","groupType":"Default","websiteThemeOverrides":{},"widgetThemeOverrides":{}});